polls/urls.py
__author__ = 'Administrator'

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/result/$', views.ResultView.as_view(), name='result'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

tutorial_polls_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace='polls'))       # find urls.py under polls/

]

polls/models.py
from django.db import models

import datetime
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    """
    创建Question 类，django会自动db中创建一个表
    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        """
           可以在数据库操作中显示字符串
        """
        return self.question_text

    def was_published_recently(self):
        """
            自定义方法，是否最近发表
        """
        return self.pub_date >= timezone.now() + datetime.timedelta(days=1)


class Choice(models.Model):
    """
    创建Choice类，django会自动在db中创建一个表：
    """
    question = models.ForeignKey(Question)     # 引入关系 one question, many choice
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        """
            可以在数据库操作中显示字符串
        """
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader, RequestContext
from .models import Question, Choice
from django.http import Http404
from django.shortcuts import get_object_or_404, get_list_or_404
from django.core.urlresolvers import reverse

from django.views import generic
# Create your views here.
# def index(req):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # # output = ','.join([q.question_text for q in latest_question_list])
#     # # return HttpResponse(output)
#     template = loader.get_template('polls/index.html')
#     context = RequestContext(req, {
#         'latest_question_list': latest_question_list,
#     })
#     return HttpResponse(template.render(context))
#
# def detail(req, question_id):
#     # try:
#     #     question = Question.objects.get(pk = question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exit")
#     question = get_object_or_404(Question, pk=question_id)
#     return render(req, 'polls/detail.html', {'question': question})
#
#
# def result(req, question_id):
#     # return HttpResponse("You're looking at result of question %s." % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     return render(req, 'polls/result.html', {'question': question})

# 使用 generic view
# generic.ListView 用于显示一个列表的数据对象
class IndexView(generic.ListView):
    # 指定显示的url字符串，默认是 <app name>/<model name>_detail.html.
    template_name = 'polls/index.html'
    # context_object_name = '' # 指定list 对象的名字，默认为 <模块名（question）>_list
    # 使用默认的名字 需要修改模板以匹配

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    template_name = 'polls/detail.html'
    model = Question

class ResultView(generic.DetailView):
    template_name = 'polls/result.html'
    model = Question

def vote(req, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=req.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(req, "polls/detail.html", {'question': question, 'error_message': "You didn't select a choice"})

    else:
        selected_choice.votes += 1
        selected_choice.save()
        # 成功处理一个POST 数据之后，需要 重定向防止用户使用back 而提交多次
        return HttpResponseRedirect(reverse("polls:result", args=(question.id,)))

polls/templates/polls/detail.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title></title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
<ul>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>
</ul>
</body>
</html>

polls/templates/polls/index.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
{#        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
        <li><a href=" {% url 'polls:detail' question.id %}">{{ question.question_text }}</a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Vote again?</a>